name: tagpr

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    name: tagpr
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
      id-token: write
      attestations: write
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.WORKFLOW_KICKER_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_KICKER_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: read

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - uses: Songmu/tagpr@9d0f650553240dab1fa907eca27e3fd5b586e538 # v1.18.1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Release
        if: steps.tagpr.outputs.tag != ''
        uses: cli/gh-extension-precompile@9e2237c30f869ad3bcaed6a4be2cd43564dd421b # v2.1.0
        with:
          generate_attestations: true
          go_version_file: go.mod
          github_token: ${{ steps.generate_token.outputs.token }}
